Profile page (step 1 - 6)
robgutierrez1/CodeU-Spring-2018 pull request #7
Opened 2018-04-11 23:01 UTC by rosafish

Created profile page for a user that has a "about me" section and a "past messages" section. "about me" can be edited by the user and updates accordingly. "past messages" are displayed by time order of conversation and follows time order within each conversation.

2018-04-18 23:59 UTC, tsurantino commented on src/main/java/codeu/controller/UserServlet.java
> +/** Servlet class responsible for the conversations page. */
This should be updated to refer to the "User" or "Profile" page rather than Conversations page.

2018-04-19 00:23 UTC, tsurantino requested changes
Just a few minor nits about comment and naming, otherwise it looks good to go.

2018-04-19 00:23 UTC, tsurantino commented on src/main/webapp/WEB-INF/view/user.jsp
> +      style="width:75%; margin-left:auto; margin-right:auto; margin-top: 50px;">
We shouldn't be putting these styling rules in the HTML markup. Can you please move these to a separate CSS file that's referenced on this page?

2018-04-19 00:23 UTC, tsurantino commented on src/main/webapp/WEB-INF/view/user.jsp
> +  <style>
You should move this to a separate file, ie. main.css

2018-04-19 00:23 UTC, tsurantino commented on src/main/java/codeu/controller/UserServlet.java
> +/** Servlet class responsible for the conversations page. */
Nit: but this should say User/Profile, not conversations.

2018-04-19 00:23 UTC, tsurantino commented on src/main/java/codeu/controller/UserServlet.java
> +   * data. It uses this to create a new Conversation object that it adds to the model.
These comments should be updated to reflect what is actually happening.

2018-04-19 00:23 UTC, tsurantino commented on src/main/java/codeu/controller/UserServlet.java
> +        user.setAboutMe(enteredAboutMe);
Indentation looks weird here, could you please update?

2018-04-19 00:23 UTC, tsurantino commented on src/main/java/codeu/model/store/basic/UserStore.java
> +  /** Add a new user to the current set of users known to the application.*/
This comment doesn't look like it's describing the function.

2018-04-19 00:23 UTC, tsurantino commented on src/main/java/codeu/model/store/persistence/PersistentDataStore.java
> +          entity.removeProperty("aboutme");
Do we necessarily need to remove the property? Doesn't setProperty just override this field?

2018-04-19 01:15 UTC, hyang344 commented on src/main/java/codeu/controller/UserServlet.java
> +   * data. It uses this to create a new Conversation object that it adds to the model.
Just changed :)

2018-04-19 01:15 UTC, hyang344 commented on src/main/java/codeu/controller/UserServlet.java
> +/** Servlet class responsible for the conversations page. */
Just changed :)

2018-04-19 01:15 UTC, hyang344 commented on src/main/java/codeu/controller/UserServlet.java
> +        user.setAboutMe(enteredAboutMe);
Just changed :)

2018-04-28 01:14 UTC, closed without merging